'use client'

import { useState } from 'react'
import { motion } from 'framer-motion'
import { ArrowRight, BrainCircuit, Camera, ChevronDown, Cpu, Droplets, ExternalLink, Eye, Gauge, Leaf, Menu, Network, PanelTop, Ruler, ScanLine, Sprout, Terminal, X, Zap } from 'lucide-react'

const images = {
  hero: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG-20260731-WA0010-BAupcxU9L9jMfA3zJUdH9L7RulcMci.jpg',
  overview: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG-20260731-WA0009-hdaYhJKX1NvnXd8qYztcKpabu2Wqd1.jpg',
  architecture: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG-20260731-WA0012-RbT4BkIDHgpGk0Q6j2RfAzgy02leFs.jpg',
  cad: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG-20260731-WA0013-vHM4RjDh8cdFd2Cxp3m3fr17iU7YzC.jpg',
  workflow: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG-20260731-WA0008-jEOfj97rlte6nPbMit7N3q0FnQv1Pu.jpg',
}

const nav = ['System', 'Architecture', 'Impact', 'Roadmap']
const tabs = [
  { id: 'mechanical', label: 'Mechanical', icon: Ruler, title: 'Mechanical infrastructure', text: 'A rigid gantry frame supported by four reinforced corner pillars enables independent Cartesian movement across the cultivation area. Heavy-duty linear guide rails and steel-reinforced timing belts provide smooth movement and positional accuracy. The Z-axis uses a precision lead-screw actuator for planting depth control.', specs: ['Cartesian X, Y, Z kinematics', '7 × 7 meter operational workspace', 'Linear guide rails + reinforced timing belts', 'Precision lead-screw Z actuator'] },
  { id: 'embedded', label: 'Embedded control', icon: Cpu, title: 'Hierarchical embedded control', text: 'A Raspberry Pi functions as the central processing unit for image acquisition, AI algorithms, path planning, scheduling, and software communication. An Arduino Mega executes motor commands, processes G-code, generates stepper pulses, and coordinates actuators with high timing accuracy.', specs: ['Raspberry Pi high-level controller', 'Arduino Mega real-time motion controller', 'G-code + serial communication', 'GRBL stepper motor coordination'] },
  { id: 'vision', label: 'Computer vision', icon: Camera, title: 'Field perception layer', text: 'A high-resolution RGB camera captures the cultivation area as the gantry traverses the field in a systematic raster pattern. OpenCV constructs a digital field map and analyzes soil surfaces, empty cultivation areas, existing plants, surface obstacles, and coordinate references.', specs: ['RGB camera image acquisition', 'OpenCV image processing', 'Raster scanning pattern', 'Terrain, obstacle and zone analysis'] },
  { id: 'ai', label: 'AI & planning', icon: BrainCircuit, title: 'Intelligent decisions', text: 'AI transforms raw environmental data into planting decisions. Algorithms evaluate plant spacing, row alignment, coverage optimization, collision avoidance, and motion efficiency, then convert generated coordinates into motion commands.', specs: ['Plant spacing + row alignment', 'Coverage optimization', 'Collision avoidance', 'Future ML cycle optimization'] },
  { id: 'planting', label: 'Precision planting', icon: Sprout, title: 'Controlled seed placement', text: 'At every target coordinate, the Z-axis lowers the tool, a motorized dibber creates a precise hole, the dispenser releases a single seed, and the tool retracts. This guarantees consistent depth and spacing with minimal soil disturbance.', specs: ['Motorized dibber', 'Single-seed dispensing', 'Configurable 1–5 cm depth', 'Automated tool retraction'] },
  { id: 'irrigation', label: 'Smart irrigation', icon: Droplets, title: 'Localized water management', text: 'Distributed capacitive moisture sensors continuously measure soil conditions. When moisture drops below predefined thresholds, a diaphragm water pump and electronically controlled solenoid valves deliver water only where it is required.', specs: ['Capacitive real-time sensors', 'Diaphragm water pump', 'Electronic solenoid valves', 'Threshold-driven scheduling'] },
]

const impacts = [
  ['Community', 'The robot improves planting and irrigation efficiency while reducing manual effort and operational complexity. It addresses labor shortages, conserves freshwater through precision irrigation, and provides educational institutions with an advanced platform for AI, embedded systems, robotics, automation, and smart agriculture research.'],
  ['Economic', 'Automation reduces labor expenses, water consumption and irrigation costs, seed waste, manual planting errors, and increases crop consistency, productivity, and long-term farming profitability.'],
  ['Environmental', 'Localized watering minimizes unnecessary irrigation and water wastage, prevents excessive seed consumption, lowers energy usage by optimizing robot movement, and supports sustainable agricultural practices.'],
  ['Educational & research', 'The platform integrates Artificial Intelligence, Robotics, Embedded Systems, Computer Vision, IoT, Mechanical Design, and Automation Engineering. Its modular architecture supports future AI, autonomous navigation, wireless communication, and predictive agricultural analytics.'],
  ['Market', 'A scalable, modular solution for smart greenhouses, educational laboratories, agricultural research centers, small and medium-sized farms, and commercial indoor farming facilities. The design can be customized for different crops, environments, and operating requirements.'],
]

const months = ['M1','M2','M3','M4','M5','M6','M7','M8','M9','M10']
const timeline = [
  ['Literature Review & Requirement Analysis', [1,2]], ['System Design & CAD Modeling', [1,2]], ['Hardware Procurement', [2,3]], ['Mechanical Structure Assembly', [3,4]], ['Motion System Installation', [3,4]], ['Electronics Integration', [4,5]], ['Embedded Programming', [4,5,6]], ['Computer Vision Development', [5,6,7]], ['AI Algorithm Development', [5,6,7]], ['Irrigation System Integration', [5,6]], ['System Integration', [6,7]], ['Testing & Calibration', [7,8]], ['Performance Evaluation', [8,9]], ['Documentation & Final Report', [9,10]], ['Final Presentation & Demonstration', [10]],
]
const budget = [['Mechanical structure', 'Aluminum profiles, rails, belts and frame components', '—'], ['Motion system', 'Linear motion and transmission components', '—'], ['Stepper motors', 'X/Y/Z actuation motors and drivers', '—'], ['Processing', 'Raspberry Pi, Arduino Mega and control electronics', '—'], ['Vision', 'RGB camera and computer vision components', '—'], ['Irrigation', 'Pump, valves, tubing and moisture sensors', '—'], ['Power', '24 V DC supply and electrical distribution', '—']]

function Reveal({ children, className = '' }: { children: React.ReactNode; className?: string }) { return <motion.div className={className} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: '-80px' }} transition={{ duration: .6 }}>{children}</motion.div> }
function SectionHeading({ eyebrow, title, copy }: { eyebrow: string; title: string; copy: string }) { return <div className="mb-12 max-w-3xl"><p className="mb-4 font-mono text-xs uppercase tracking-[.22em] text-emerald-400">{eyebrow}</p><h2 className="text-3xl font-semibold tracking-tight text-zinc-50 sm:text-5xl">{title}</h2><p className="mt-5 text-base leading-8 text-zinc-400">{copy}</p></div> }

export default function Page() {
  const [activeTab, setActiveTab] = useState('mechanical')
  const [openImpact, setOpenImpact] = useState(0)
  const [menuOpen, setMenuOpen] = useState(false)
  const active = tabs.find((tab) => tab.id === activeTab) ?? tabs[0]
  return <main className="min-h-screen overflow-hidden bg-[#09090b] text-zinc-100 selection:bg-emerald-400 selection:text-black">
    <nav className="fixed inset-x-0 top-0 z-50 border-b border-white/10 bg-[#09090b]/80 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8"><a href="#top" className="font-mono text-xs font-semibold tracking-[.18em] text-zinc-100">AGPR<span className="text-emerald-400">/01</span></a><div className="hidden items-center gap-8 md:flex">{nav.map((item) => <a key={item} href={`#${item.toLowerCase()}`} className="text-sm text-zinc-400 transition hover:text-emerald-400">{item}</a>)}</div><button className="md:hidden" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle navigation">{menuOpen ? <X /> : <Menu />}</button></div>{menuOpen && <div className="border-t border-white/10 bg-[#09090b] px-5 py-4 md:hidden">{nav.map(item => <a key={item} href={`#${item.toLowerCase()}`} onClick={() => setMenuOpen(false)} className="block py-3 text-sm text-zinc-300">{item}</a>)}</div>}</nav>
    <section id="top" className="relative flex min-h-[92vh] items-end"><img src={images.hero} alt="Autonomous gantry farming robot in a greenhouse" className="absolute inset-0 size-full object-cover object-center opacity-35" /><div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_30%,rgba(16,185,129,.15),transparent_30%),linear-gradient(90deg,#09090b_15%,rgba(9,9,11,.7),rgba(9,9,11,.2))]" /><div className="relative mx-auto w-full max-w-7xl px-5 pb-24 pt-40 lg:px-8"><Reveal><div className="max-w-4xl"><div className="mb-7 flex items-center gap-3 font-mono text-xs uppercase tracking-[.2em] text-emerald-400"><span className="size-2 rounded-full bg-emerald-400 shadow-[0_0_18px_#10b981]" /> Sohag University · AI / Robotics / Smart Agriculture</div><h1 className="max-w-4xl text-5xl font-semibold leading-[.98] tracking-[-.05em] text-zinc-50 sm:text-7xl lg:text-8xl">Autonomous <span className="text-emerald-400">3-Axis</span><br />Gantry Precision<br />Farming Robot</h1><p className="mt-8 max-w-2xl text-lg leading-8 text-zinc-300">An intelligent robotic platform that scans a 50-square-meter field, analyzes soil conditions, plants seeds with configurable precision, and irrigates only where needed.</p><div className="mt-10 flex flex-wrap gap-4"><a href="#system" className="group inline-flex items-center gap-3 rounded-full bg-emerald-400 px-6 py-3 font-medium text-zinc-950 transition hover:bg-emerald-300">Explore the system <ArrowRight className="transition group-hover:translate-x-1" /></a><a href="#roadmap" className="inline-flex items-center gap-3 rounded-full border border-white/20 px-6 py-3 text-zinc-200 transition hover:border-emerald-400 hover:text-emerald-400">View 10-month roadmap</a></div></div></Reveal></div></section>
    <section id="system" className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><SectionHeading eyebrow="01 / The opportunity" title="From uniform farming to site-specific intelligence." copy="Agriculture faces labor shortages, inefficient resource utilization, inconsistent planting accuracy, and excessive water consumption. This project replaces uniform treatment with a coordinated system that senses, reasons, moves, plants, and waters with minimal human intervention." /><div className="grid gap-5 md:grid-cols-2"><Reveal className="group rounded-3xl border border-white/10 bg-zinc-900/60 p-8 transition hover:border-emerald-400/50"><ScanLine className="mb-12 text-emerald-400" /><h3 className="text-2xl font-medium">Problem definition</h3><p className="mt-4 leading-8 text-zinc-400">Traditional farming is time-consuming, labor-intensive, and susceptible to human error. Uniform seed distribution ignores variations in soil and moisture, causing uneven growth, reduced yield, seed waste, and unnecessary water use. Existing machinery is often expensive, supervision-heavy, and inaccessible to small farms, research institutions, and educational environments.</p></Reveal><Reveal className="group rounded-3xl border border-emerald-400/20 bg-emerald-400/[.06] p-8 transition hover:border-emerald-400/60"><Zap className="mb-12 text-emerald-400" /><h3 className="text-2xl font-medium">Project motivation</h3><p className="mt-4 leading-8 text-zinc-400">Rapid population growth, climate change, and shrinking agricultural resources make efficient food production critical. The objective is an affordable, modular research platform that integrates AI, computer vision, IoT, robotics, and precision agriculture without expensive industrial equipment.</p></Reveal></div></section>
    <section className="border-y border-white/10 bg-[#121214] py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionHeading eyebrow="02 / Operational loop" title="One closed-loop workflow." copy="Environmental perception becomes an actionable field plan, then a precise physical operation. Every step contributes to higher productivity and lower resource consumption." /><div className="grid gap-4 md:grid-cols-4">{[['01','Scan','RGB camera captures a raster scan of the cultivation area.',Camera],['02','Analyze','OpenCV and AI identify soil, zones, obstacles and coordinates.',BrainCircuit],['03','Plant','The Z-axis places one seed at a configurable depth.',Sprout],['04','Irrigate','Moisture thresholds trigger localized water delivery.',Droplets]].map(([num,title,copy,Icon]) => <Reveal key={String(num)} className="relative rounded-2xl border border-white/10 bg-[#18181b] p-6"><span className="font-mono text-xs text-emerald-400">{num}</span><Icon className="my-10 text-zinc-300" /><h3 className="text-xl font-medium">{title}</h3><p className="mt-3 text-sm leading-6 text-zinc-400">{copy}</p></Reveal>)}</div><img src={images.workflow} alt="Robot workflow and dashboard visual" className="mt-12 h-72 w-full rounded-3xl border border-white/10 object-cover object-bottom opacity-80" /></div></section>
    <section id="architecture" className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><SectionHeading eyebrow="03 / Technical architecture" title="A modular stack built for expansion." copy="Each subsystem operates independently while communicating through standardized interfaces. Select a layer to inspect the exact engineering approach and tools." /><div className="grid gap-8 lg:grid-cols-[.8fr_1.2fr]"><div className="flex gap-2 overflow-x-auto pb-2 lg:flex-col">{tabs.map(tab => { const Icon = tab.icon; return <button key={tab.id} onClick={() => setActiveTab(tab.id)} className={`flex min-w-max items-center gap-3 rounded-xl px-4 py-3 text-left text-sm transition lg:w-full ${activeTab === tab.id ? 'bg-emerald-400 text-zinc-950' : 'border border-white/10 text-zinc-400 hover:border-emerald-400/40 hover:text-zinc-100'}`}><Icon />{tab.label}</button> })}</div><motion.div key={active.id} initial={{ opacity: 0, x: 12 }} animate={{ opacity: 1, x: 0 }} className="rounded-3xl border border-white/10 bg-zinc-900/70 p-7 lg:p-10"><div className="flex items-start justify-between gap-4"><div><p className="font-mono text-xs uppercase tracking-[.2em] text-emerald-400">{active.label}</p><h3 className="mt-3 text-3xl font-medium">{active.title}</h3></div><active.icon className="text-emerald-400" /></div><p className="mt-6 leading-8 text-zinc-400">{active.text}</p><div className="mt-8 grid gap-3 sm:grid-cols-2">{active.specs.map(spec => <div key={spec} className="rounded-xl border border-white/10 bg-black/20 p-4 font-mono text-xs text-zinc-300">{spec}</div>)}</div></motion.div></div><div className="mt-12 grid gap-5 lg:grid-cols-2"><img src={images.architecture} alt="System architecture diagram showing hardware, electronic and software layers" className="h-full min-h-72 w-full rounded-3xl border border-white/10 object-cover" /><div className="rounded-3xl border border-white/10 bg-zinc-900/60 p-8"><p className="font-mono text-xs uppercase tracking-[.2em] text-emerald-400">Software toolchain</p><div className="mt-8 grid gap-4 sm:grid-cols-2">{[['Python','AI algorithms and system coordination'],['OpenCV','Image processing and terrain analysis'],['Arduino C/C++','Motion control firmware'],['GRBL Firmware','Stepper motor coordination'],['Raspberry Pi OS','High-level system execution'],['G-Code','Motion command generation'],['Serial Communication','Raspberry Pi–Arduino communication']].map(([a,b]) => <div key={a}><p className="font-mono text-sm text-zinc-100">{a}</p><p className="mt-1 text-sm leading-6 text-zinc-500">{b}</p></div>)}</div></div></div></section>
    <section className="border-y border-white/10 bg-[#121214] py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionHeading eyebrow="04 / System intelligence" title="The operator sees the whole field." copy="The user control interface is designed for educational and practical agricultural environments: simple enough to operate, rich enough to coordinate a complete farming cycle." /><div className="grid items-center gap-10 lg:grid-cols-[1.1fr_.9fr]"><div className="rounded-3xl border border-white/10 bg-[#09090b] p-3 shadow-2xl shadow-emerald-950/30"><img src={images.overview} alt="Smart Farm Bot dashboard and operating scenes" className="w-full rounded-2xl" /></div><div className="grid gap-3">{['Configure planting parameters','Start or stop farming operations','Monitor system status','View field maps','Schedule irrigation cycles','Review operational statistics','Receive maintenance notifications'].map((item, i) => <div key={item} className="flex items-center gap-4 rounded-xl border border-white/10 bg-zinc-900/60 p-4"><span className="font-mono text-xs text-emerald-400">0{i+1}</span><span className="text-sm text-zinc-300">{item}</span></div>)}</div></div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><SectionHeading eyebrow="05 / Market position" title="More than a single-purpose machine." copy="The proposed platform combines autonomous motion control, computer vision, precision planting, moisture-based irrigation, and modular software architecture in one coordinated system." /><div className="overflow-x-auto rounded-3xl border border-white/10"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-zinc-900/80 text-xs uppercase tracking-wider text-zinc-500"><tr><th className="p-5">Capability</th><th className="p-5 text-emerald-400">Proposed robot</th><th className="p-5">FarmBot</th><th className="p-5">Agricultural drones</th></tr></thead><tbody className="divide-y divide-white/10">{[['Fixed precision','Highly accurate fixed gantry','Cartesian mechanism','Aerial inspection'],['Planting','Automated seed placement + depth control','Automated planting','Cannot deposit seeds'],['Irrigation','Localized, moisture-driven','Automated watering','Cannot irrigate locally'],['Intelligence','Computer vision + AI planning','Limited AI and basic environmental analysis','Crop health monitoring'],['Deployment','Research, education, greenhouses','Home gardens and education','Large-area inspection']].map(row => <tr key={row[0]} className="text-zinc-300"><td className="p-5 font-medium text-zinc-100">{row[0]}</td>{row.slice(1).map(cell => <td key={cell} className="p-5 text-zinc-400">{cell}</td>)}</tr>)}</tbody></table></div><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{['Fixed gantry architecture providing highly accurate positioning','Integration of computer vision with precision planting','Automated seed placement and localized irrigation within one system','Modular hardware and software architecture for future expansion','Lower implementation complexity for educational and research environments','Scalable platform suitable for smart farming experimentation'].map(item => <div key={item} className="rounded-xl border border-emerald-400/20 bg-emerald-400/[.04] p-4 text-sm leading-6 text-zinc-300">{item}</div>)}</div></section>
    <section id="impact" className="border-y border-white/10 bg-[#121214] py-24"><div className="mx-auto max-w-4xl px-5 lg:px-8"><SectionHeading eyebrow="06 / Why this project" title="Impact across the ecosystem." copy="The robot demonstrates how modern automation can transform agriculture from a labor-intensive industry into a data-driven, intelligent production system." /><div className="flex flex-col gap-3">{impacts.map(([title, text], index) => <div key={title} className="rounded-2xl border border-white/10 bg-zinc-900/60"><button onClick={() => setOpenImpact(openImpact === index ? -1 : index)} className="flex w-full items-center justify-between p-5 text-left"><span className="text-lg font-medium">{title}</span><ChevronDown className={`text-emerald-400 transition ${openImpact === index ? 'rotate-180' : ''}`} /></button>{openImpact === index && <motion.p initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: 'auto' }} className="px-5 pb-6 leading-8 text-zinc-400">{text}</motion.p>}</div>)}</div></div></section>
    <section id="roadmap" className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><SectionHeading eyebrow="07 / Delivery plan" title="Ten months from requirements to demonstration." copy="Sequential phases ensure systematic development, testing, and validation of the robotic farming platform." /><div className="overflow-x-auto rounded-3xl border border-white/10 bg-zinc-900/50 p-5"><div className="min-w-[760px]"><div className="grid grid-cols-[minmax(240px,1.8fr)_repeat(10,1fr)] gap-1 pb-3 font-mono text-[10px] text-zinc-500"><span>PROJECT ACTIVITY</span>{months.map(m => <span key={m} className="text-center">{m}</span>)}</div>{timeline.map(([label, activeMonths]) => <div key={String(label)} className="grid grid-cols-[minmax(240px,1.8fr)_repeat(10,1fr)] items-center gap-1 border-t border-white/5 py-2"><span className="pr-4 text-xs text-zinc-300">{label}</span>{months.map((_, i) => <span key={i} className={`mx-auto size-3 rounded-full ${Array.isArray(activeMonths) && activeMonths.includes(i + 1) ? 'bg-emerald-400 shadow-[0_0_12px_#10b981]' : 'bg-zinc-800'}`} />)}</div>)}</div></div><div className="mt-10 grid gap-8 lg:grid-cols-[1fr_.7fr]"><div className="overflow-x-auto rounded-3xl border border-white/10"><table className="w-full min-w-[600px] text-left text-sm"><thead className="bg-zinc-900 text-zinc-400"><tr><th className="p-5">Budget line</th><th className="p-5">Scope</th><th className="p-5">Value</th></tr></thead><tbody>{budget.map(([a,b,c]) => <tr key={a} className="border-t border-white/10"><td className="p-5 font-medium">{a}</td><td className="p-5 text-zinc-500">{b}</td><td className="p-5 font-mono text-zinc-400">{c}</td></tr>)}</tbody></table><div className="border-t border-emerald-400/20 bg-emerald-400/[.06] p-5 text-sm text-zinc-300">The proposal specifies an estimated total budget of <strong className="text-emerald-400">$3,050 = 150k EGP</strong>. The source PDF does not provide item-level currency values, so no amounts have been fabricated.</div></div><div className="rounded-3xl border border-emerald-400/30 bg-emerald-400/[.06] p-8"><p className="font-mono text-xs uppercase tracking-[.2em] text-emerald-400">Final product</p><h3 className="mt-4 text-3xl font-medium">A complete intelligent precision farming system.</h3><p className="mt-5 leading-8 text-zinc-400">Autonomous scanning, intelligent planting planning, precise seed placement, soil moisture monitoring, automated irrigation, coordinated movement, and reliable real-time operation.</p><a href={images.cad} target="_blank" rel="noreferrer" className="mt-8 inline-flex items-center gap-2 text-sm text-emerald-400 hover:text-emerald-300">Open engineering drawing <ExternalLink /></a></div></div></section>
    <footer className="border-t border-white/10 px-5 py-10 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-5 text-sm text-zinc-500 sm:flex-row"><span className="font-mono text-zinc-300">AGPR / 01</span><span>Autonomous 3-Axis Gantry Precision Farming Robot · Sohag University</span><span className="font-mono">50 m² · ±1 mm · 24 V DC</span></div></footer>
  </main>
}
